
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Mar 25 17:00:05 EDT 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class A3Symbol {
  /* terminals */
  public static final int TIMES = 4;
  public static final int READ = 21;
  public static final int ELSE = 19;
  public static final int SEMICOLON = 11;
  public static final int PLUS = 2;
  public static final int INT = 22;
  public static final int RPAREN = 7;
  public static final int EQUAL = 8;
  public static final int RETURN = 17;
  public static final int END = 15;
  public static final int IF = 18;
  public static final int LPAREN = 6;
  public static final int WRITE = 20;
  public static final int ID = 12;
  public static final int BEGIN = 14;
  public static final int STRING = 23;
  public static final int COMMA = 10;
  public static final int NUMBER = 27;
  public static final int EOF = 0;
  public static final int NEQUAL = 9;
  public static final int DIVIDE = 5;
  public static final int MAIN = 25;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int ASSIGN = 16;
  public static final int QSTRING = 13;
  public static final int REAL = 24;
  public static final int JUNK = 26;
}

