
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Mar 25 16:34:43 EDT 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class testSymbol {
  /* terminals */
  public static final int MINUS = 3;
  public static final int DIVIDE = 5;
  public static final int NUMBER = 9;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int error = 1;
  public static final int RPAREN = 7;
  public static final int JUNK = 8;
  public static final int TIMES = 4;
  public static final int LPAREN = 6;
}

