
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Apr 08 14:44:34 EDT 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class A5Sym {
  /* terminals */
  public static final int READ = 17;
  public static final int ELSE = 15;
  public static final int INT = 20;
  public static final int RPAREN = 5;
  public static final int EQEVAL = 8;
  public static final int SEMI = 6;
  public static final int END = 12;
  public static final int RETURN = 13;
  public static final int TRUE = 18;
  public static final int IF = 14;
  public static final int LPAREN = 4;
  public static final int ID = 25;
  public static final int WRITE = 16;
  public static final int BEGIN = 11;
  public static final int QUOTED = 24;
  public static final int STRING = 23;
  public static final int COMMA = 7;
  public static final int NUMBER = 22;
  public static final int EOF = 0;
  public static final int MAIN = 10;
  public static final int FALSE = 19;
  public static final int error = 1;
  public static final int ASSIGN = 9;
  public static final int OP_PM = 2;
  public static final int REAL = 21;
  public static final int OP_MD = 3;
}

